#!/usr/bin/env python
"""Synthetic demonstration plant — parametric IFC4 generator (self-owned, NOT a real model).

Emits an honest **synthetic demonstration model**: a tank farm (IfcTank), a pump skid
(IfcPump), the header/branch pipe runs that connect them (IfcFlowSegment — repeated
geometry, instancing-friendly by design) and inline shutoff valves (IfcValve) on the
branches. Every element carries a real GlobalId and property sets (capacity / flow / head /
service / line-id) so the whole twin pipeline runs unmodified: import (ifc_convert.py) →
sidecar join → optimize → bind → verify. It is the pitch/plant demo asset that no
qualifying public model delivered (sourcing spike: docs → plant-demo-asset verdicts) — the
plant vocabulary the sim's DEMO_TAGS (pump temp/flow, tank level, valve position, motor rpm)
was already written against, now bound to literal plant geometry.

HONESTY: this is a generated demonstration model. It has NO real-world provenance and must
never be presented as a surveyed or as-built plant. The label "synthetic demonstration
model" is written into the IFC FILE_DESCRIPTION header and this file's docstring on purpose.

VENV: needs ifcopenshell, which has NO wheel for Python 3.14 — run inside the SAME pinned
3.12 venv the rest of the pipeline uses (see tools/ifc_convert.py's header):

    uv venv --python 3.12 .venv-ifc
    uv pip install --python .venv-ifc/bin/python ifcopenshell==0.8.5
    .venv-ifc/bin/python plugin/examples/gen_plant_ifc.py --out plant.ifc

DETERMINISM: same --seed ⇒ byte-identical file (identical sha256). ifcopenshell.guid.new()
is random, so this generator does NOT use it: it seeds its own PRNG and derives every
GlobalId from that stream via ifcopenshell.guid.compress(uuid-from-rng). The two other
sources of run-to-run drift are pinned too — the STEP header time_stamp and every
IfcOwnerHistory CreationDate are FIXED constants (never wall-clock). The only value outside
our control is the ifcopenshell build hash baked into preprocessor_version, which is stable
for a pinned 0.8.5 install, so two runs of the same --seed on the same install are
byte-identical (proven: see the plant-demo-asset kit-build handoff).

Usage:
    gen_plant_ifc.py [--tanks N] [--pumps M] [--valves K] [--seed S] [--out plant.ifc]

The DEFAULT (4 tanks, 3 pumps) is the vendored demo asset — small, fast, a good screenshot,
and ≥6 bindable tags across ≥3 equipment classes. Turn the knobs up for a marketing-scale
model / the optimizer's instancing showcase (the pipe runs are the repeated geometry).
"""

import argparse
import random
import uuid

import ifcopenshell
import ifcopenshell.guid

# --- pinned constants (determinism contract — never wall-clock) --------------------------
# A fixed ISO time_stamp / CreationDate so the STEP output is byte-identical per seed. The
# date is arbitrary-but-fixed (the spike date); it carries no meaning beyond "not now()".
FIXED_TIMESTAMP = "2026-07-10T00:00:00"
FIXED_EPOCH = 1783036800  # 2026-07-10T00:00:00Z as a Unix int, for IfcOwnerHistory.
SYNTHETIC_LABEL = "synthetic demonstration model"

# --- layout constants (metres) — a calm tank-farm / pump-skid arrangement ----------------
TANK_RADIUS = 1.5
TANK_HEIGHT = 5.0
TANK_SPACING = 6.0
TANK_ROW_Y = 0.0

PUMP_DX, PUMP_DY, PUMP_DZ = 1.4, 0.8, 1.0
PUMP_SPACING = 6.0
PUMP_ROW_Y = -10.0

PIPE_RADIUS = 0.25
PIPE_SEG_LEN = 4.0  # identical segment length ⇒ the header is many identical meshes.
HEADER_Y = -4.0
HEADER_Z = 0.5

VALVE_SIZE = 0.6  # cube-ish inline valve body.


def build_plant(tanks: int, pumps: int, valves: int, seed: int) -> ifcopenshell.file:
    """Author the synthetic plant into a fresh IFC4 file. Pure function of the args + seed."""
    rng = random.Random(seed)

    def new_guid() -> str:
        # Deterministic GlobalId: a 128-bit draw from the seeded PRNG, compressed to the
        # 22-char IFC id — NOT ifcopenshell.guid.new() (which is uuid4-random).
        return ifcopenshell.guid.compress(uuid.UUID(int=rng.getrandbits(128)).hex)

    f = ifcopenshell.file(schema="IFC4")

    # Honest "synthetic" label in the STEP header (survives the round-trip; visible in any
    # IFC header check) + a pinned time_stamp for byte-identical output.
    hdr = f.header
    hdr.file_name.name = "synthetic-plant.ifc"
    hdr.file_name.time_stamp = FIXED_TIMESTAMP
    hdr.file_name.author = ("xenodot-twin gen_plant_ifc",)
    hdr.file_name.organization = ("xenodot-twin",)
    hdr.file_name.authorization = "self-owned synthetic demonstration model"
    hdr.file_description.description = (
        "ViewDefinition [ReferenceView]",
        "Synthetic demonstration model - generated by xenodot-twin gen_plant_ifc.py; "
        "no real-world provenance.",
    )

    # --- owner / application / context ---------------------------------------------------
    person = f.create_entity("IfcPerson", FamilyName="Synthetic")
    org = f.create_entity("IfcOrganization", Name="xenodot-twin")
    p_and_o = f.create_entity(
        "IfcPersonAndOrganization", ThePerson=person, TheOrganization=org
    )
    app = f.create_entity(
        "IfcApplication",
        ApplicationDeveloper=org,
        Version="0.8.5",
        ApplicationFullName="gen_plant_ifc",
        ApplicationIdentifier="gen_plant_ifc",
    )
    owner = f.create_entity(
        "IfcOwnerHistory",
        OwningUser=p_and_o,
        OwningApplication=app,
        ChangeAction="ADDED",
        CreationDate=FIXED_EPOCH,
    )

    length_unit = f.create_entity("IfcSIUnit", UnitType="LENGTHUNIT", Name="METRE")
    units = f.create_entity("IfcUnitAssignment", Units=[length_unit])
    origin = f.create_entity("IfcCartesianPoint", Coordinates=(0.0, 0.0, 0.0))
    z_axis = f.create_entity("IfcDirection", DirectionRatios=(0.0, 0.0, 1.0))
    x_axis = f.create_entity("IfcDirection", DirectionRatios=(1.0, 0.0, 0.0))
    world = f.create_entity(
        "IfcAxis2Placement3D", Location=origin, Axis=z_axis, RefDirection=x_axis
    )
    ctx = f.create_entity(
        "IfcGeometricRepresentationContext",
        ContextType="Model",
        CoordinateSpaceDimension=3,
        Precision=1e-5,
        WorldCoordinateSystem=world,
    )
    f.create_entity(
        "IfcProject",
        GlobalId=new_guid(),
        OwnerHistory=owner,
        Name="Synthetic Demonstration Plant",
        Description=SYNTHETIC_LABEL,
        RepresentationContexts=[ctx],
        UnitsInContext=units,
    )

    # --- geometry helpers ----------------------------------------------------------------
    def dir3(x: float, y: float, z: float):
        return f.create_entity("IfcDirection", DirectionRatios=(x, y, z))

    def placement(x: float, y: float, z: float, axis=None, refdir=None):
        loc = f.create_entity("IfcCartesianPoint", Coordinates=(x, y, z))
        kwargs = {"Location": loc}
        if axis is not None:
            kwargs["Axis"] = axis
        if refdir is not None:
            kwargs["RefDirection"] = refdir
        a2p = f.create_entity("IfcAxis2Placement3D", **kwargs)
        return f.create_entity("IfcLocalPlacement", RelativePlacement=a2p)

    prof_origin_2d = f.create_entity(
        "IfcAxis2Placement2D",
        Location=f.create_entity("IfcCartesianPoint", Coordinates=(0.0, 0.0)),
    )
    extrude_dir = dir3(0.0, 0.0, 1.0)  # every solid extrudes along its own local +Z.

    def shape_of(solid):
        rep = f.create_entity(
            "IfcShapeRepresentation",
            ContextOfItems=ctx,
            RepresentationIdentifier="Body",
            RepresentationType="SweptSolid",
            Items=[solid],
        )
        return f.create_entity("IfcProductDefinitionShape", Representations=[rep])

    def cylinder(radius: float, depth: float):
        profile = f.create_entity(
            "IfcCircleProfileDef",
            ProfileType="AREA",
            Position=prof_origin_2d,
            Radius=radius,
        )
        solid = f.create_entity(
            "IfcExtrudedAreaSolid",
            SweptArea=profile,
            Position=world,
            ExtrudedDirection=extrude_dir,
            Depth=depth,
        )
        return shape_of(solid)

    def box(dx: float, dy: float, dz: float):
        profile = f.create_entity(
            "IfcRectangleProfileDef",
            ProfileType="AREA",
            Position=prof_origin_2d,
            XDim=dx,
            YDim=dy,
        )
        solid = f.create_entity(
            "IfcExtrudedAreaSolid",
            SweptArea=profile,
            Position=world,
            ExtrudedDirection=extrude_dir,
            Depth=dz,
        )
        return shape_of(solid)

    def add_pset(product, name: str, props: dict) -> None:
        hp = [
            f.create_entity(
                "IfcPropertySingleValue",
                Name=k,
                NominalValue=f.create_entity("IfcText", wrappedValue=str(v)),
            )
            for k, v in props.items()
        ]
        pset = f.create_entity(
            "IfcPropertySet",
            GlobalId=new_guid(),
            OwnerHistory=owner,
            Name=name,
            HasProperties=hp,
        )
        f.create_entity(
            "IfcRelDefinesByProperties",
            GlobalId=new_guid(),
            OwnerHistory=owner,
            RelatedObjects=[product],
            RelatingPropertyDefinition=pset,
        )

    guids: dict[str, str] = {}  # ref tag -> GlobalId, echoed to stdout for map authoring.

    # --- tank farm (IfcTank) — identical vertical cylinders, a row along +X --------------
    tank_services = ["buffer", "feed", "product", "slop", "condensate", "reflux"]
    for i in range(tanks):
        ref = f"TK-{101 + i}"
        gid = new_guid()
        service = tank_services[i % len(tank_services)]
        capacity = 5000 + 500 * (rng.randrange(0, 11))  # deterministic, 5000..10000 L
        tank = f.create_entity(
            "IfcTank",
            GlobalId=gid,
            OwnerHistory=owner,
            Name=f"{ref} {service.title()} Tank",
            ObjectPlacement=placement(i * TANK_SPACING, TANK_ROW_Y, 0.0),
            Representation=cylinder(TANK_RADIUS, TANK_HEIGHT),
            PredefinedType="STORAGE",
        )
        add_pset(
            tank,
            "Pset_TankCommon",
            {
                "Reference": ref,
                "NominalCapacity": f"{capacity} L",
                "Service": service,
                "LineReference": f"L-{100 + i}",
            },
        )
        guids[ref] = gid

    # --- pump skid (IfcPump) — identical boxes, a row along +X ---------------------------
    pump_services = ["feed", "transfer", "circulation", "booster", "dosing"]
    for i in range(pumps):
        ref = f"P-{101 + i}"
        gid = new_guid()
        service = pump_services[i % len(pump_services)]
        flow = 8 + 2 * (rng.randrange(0, 21))  # 8..48 m3/h, deterministic
        head = 20 + 5 * (rng.randrange(0, 13))  # 20..80 m, deterministic
        pump = f.create_entity(
            "IfcPump",
            GlobalId=gid,
            OwnerHistory=owner,
            Name=f"{ref} {service.title()} Pump",
            ObjectPlacement=placement(i * PUMP_SPACING, PUMP_ROW_Y, 0.0),
            Representation=box(PUMP_DX, PUMP_DY, PUMP_DZ),
            PredefinedType="CIRCULATOR",
        )
        add_pset(
            pump,
            "Pset_PumpCommon",
            {
                "Reference": ref,
                "NominalFlowRate": f"{flow} m3/h",
                "NominalHead": f"{head} m",
                "Service": service,
                "LineReference": f"L-{200 + i}",
            },
        )
        guids[ref] = gid

    # --- header pipe run (IfcFlowSegment) — identical horizontal cylinder segments --------
    # Local +Z of each segment is rotated to world +X (Axis=(1,0,0)), so identical local
    # geometry ⇒ the optimizer sees repeated meshes (instancing showcase at scale).
    header_axis = dir3(1.0, 0.0, 0.0)
    header_ref = dir3(0.0, 0.0, 1.0)
    span = max(1, (max(tanks, pumps) - 1)) * max(TANK_SPACING, PUMP_SPACING)
    n_header = max(2, int(span // PIPE_SEG_LEN) + 1)
    for i in range(n_header):
        ref = f"HDR-{i + 1}"
        gid = new_guid()
        seg = f.create_entity(
            "IfcFlowSegment",
            GlobalId=gid,
            OwnerHistory=owner,
            Name=f"Header pipe {ref}",
            ObjectPlacement=placement(
                i * PIPE_SEG_LEN - 2.0, HEADER_Y, HEADER_Z, header_axis, header_ref
            ),
            Representation=cylinder(PIPE_RADIUS, PIPE_SEG_LEN),
        )
        add_pset(
            seg,
            "Pset_PipeSegmentTypeCommon",
            {"Reference": ref, "NominalDiameter": "200 mm", "LineReference": "L-HDR"},
        )
        guids[ref] = gid

    # --- branch pipes (IfcFlowSegment) + inline valves (IfcValve) --------------------------
    # One branch per pump connects the header down to the pump row (local +Z → world +Y),
    # each carrying one shutoff valve. Valve count is independent (--valves) so the tag
    # budget can be tuned; extra valves fall on the last branch.
    branch_axis = dir3(0.0, 1.0, 0.0)
    branch_ref = dir3(1.0, 0.0, 0.0)
    branch_len = abs(HEADER_Y - PUMP_ROW_Y)
    for i in range(pumps):
        bx = i * PUMP_SPACING
        bref = f"BR-{i + 1}"
        bgid = new_guid()
        branch = f.create_entity(
            "IfcFlowSegment",
            GlobalId=bgid,
            OwnerHistory=owner,
            Name=f"Branch pipe {bref}",
            ObjectPlacement=placement(bx, HEADER_Y, HEADER_Z, branch_axis, branch_ref),
            Representation=cylinder(PIPE_RADIUS, branch_len),
        )
        add_pset(
            branch,
            "Pset_PipeSegmentTypeCommon",
            {"Reference": bref, "NominalDiameter": "100 mm", "LineReference": f"L-{200 + i}"},
        )
        guids[bref] = bgid

    for i in range(valves):
        branch_i = min(i, pumps - 1) if pumps > 0 else 0
        vx = branch_i * PUMP_SPACING
        # stack extra valves along the branch so they don't overlap.
        vy = HEADER_Y - (branch_len * 0.5) - (i // max(1, pumps)) * VALVE_SIZE * 1.5
        ref = f"V-{101 + i}"
        gid = new_guid()
        valve = f.create_entity(
            "IfcValve",
            GlobalId=gid,
            OwnerHistory=owner,
            Name=f"{ref} Shutoff Valve",
            ObjectPlacement=placement(vx, vy, HEADER_Z),
            Representation=box(VALVE_SIZE, VALVE_SIZE, VALVE_SIZE),
            PredefinedType="ISOLATING",
        )
        add_pset(
            valve,
            "Pset_ValveTypeCommon",
            {
                "Reference": ref,
                "Size": "DN100",
                "Service": "isolation",
                "LineReference": f"L-{200 + branch_i}",
            },
        )
        guids[ref] = gid

    f._plant_guids = guids  # attach for the CLI to print (not part of the IFC schema).
    return f


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tanks", type=int, default=4, help="number of IfcTank (default 4)")
    ap.add_argument("--pumps", type=int, default=3, help="number of IfcPump (default 3)")
    ap.add_argument(
        "--valves",
        type=int,
        default=None,
        help="number of IfcValve (default: one per pump branch)",
    )
    ap.add_argument("--seed", type=int, default=42, help="PRNG seed (determinism, default 42)")
    ap.add_argument("--out", default="plant.ifc", help="output IFC path (default plant.ifc)")
    args = ap.parse_args()

    if args.tanks < 0 or args.pumps < 0:
        ap.error("--tanks and --pumps must be non-negative")
    valves = args.pumps if args.valves is None else args.valves
    if valves < 0:
        ap.error("--valves must be non-negative")

    f = build_plant(args.tanks, args.pumps, valves, args.seed)
    f.write(args.out)

    guids = f._plant_guids
    print(f"WROTE {args.out}  (synthetic demonstration model, seed={args.seed})")
    print(f"  tanks={args.tanks} pumps={args.pumps} valves={valves}")
    print("  GlobalIds (for binding_map authoring):")
    for ref, gid in guids.items():
        print(f"    {ref:8s} {gid}")


if __name__ == "__main__":
    main()
